config/routes.rb
Rails.application.routes.draw do

	resources :images, only: [:create, :destroy]

	resources :users do
		member do
			post 'load_dropzone_images', as: 'load_image'
		end
	end

	resource :session, only: [:new, :create, :destroy]
	resources :bands do
		resources :albums, only: [:new]
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note
		end
	end

	resources :albums, except: [:index] do
		resources :tracks, only: [:new]
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note
		end
	end

	resources :tracks, except: [:index, :new] do
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note # tracks/:id/add_note
		end
	end

	resources :genres, only: [:index, :show]
	
	delete 'notes/:id', to: "notes#destroy", as: :note
	post 'notes', to: "notes#create", as: :notes

	root 'pages#home'

end

app/models/track.rb
class Track < ActiveRecord::Base

	include Noteable
	
	validates :name, presence: true

	belongs_to :album
	has_one :band, through: :album, source: :band

	
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :require_logged_in
	before_action :set_track, only: [:show, :edit, :update, :destroy]

  def new
    @track = Track.new
  end

  def show
		@owner = @track
		@owner_notes = @track.notes
  end

  # created within albums/show
  def create
    @album = Album.find_by(id: track_params[:album_id])
		@track = @album.tracks.build(track_params)
		
		respond_to do |format|
    	if @track.save
				format.js { render 'create', status: :created, location: @track, layout: !request.xhr? }
				#format.json { render json: @track }
				format.html { redirect_to track_url(@track) }
				#format.js { render :partial => 'tracks_table', :object => @track }
				
    	else
				format.js { render @track.errors, status: :unprocessable_entity }
				#format.json { render json: @track.errors.full_messages, status: :unprocessable_entity }
				format.html do
					flash[:errors] = @track.errors.full_messages
      		redirect_to album_url(@album)
				end
			end
    end
		
  end

  def edit
  end

  def update
  end

  def destroy
  end
	
	# NOTE: need to use params[:track_id], NOT [:id]!
	def destroy_note
    @note = Note.find(params[:id])
		@owner = Track.find(params[:track_id])
		@owner_id = @owner.id
		
    @note.destroy
		# refresh
		@destroy_url = "/albums/#{@owner.id}/notes/"
		@owner_notes = @owner.notes
		
		respond_to do |format|
			
			format.html { redirect_to :back }
			format.js
		end
    
  end
	
	

  private

  def set_track
    @track = Track.includes(album: :band).find(params[:id])
    @notes = @track.notes
  end

  def track_params
    params.require(:track).permit(:name, :length, :lyrics, :track_type, :album_id)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper

  def ugly_lyrics(lyrics)
    html = "<pre style='text-align:center;'>"
    lyrics.split("\n").each do |line|
      html += "&#9835; #{line}\n"
    end
    html += "</pre>"

    html.html_safe
  end

end

app/views/tracks/_form_new.html.erb
<!--  /albums/:id  -->

<!-- Form -->
<h2>ADD A TRACK</h2>

<%= bootstrap_form_for track, url: tracks_url, method: "POST", id: "add_track_form" do |f| %>
  <!-- pass album_id as hidden field in case not going through Album#show -->
  <%= f.hidden_field :album_id, value: album.id %>
  <%= f.text_field :name %>
  <%= f.time_select :length %>
  <%= f.select :track_type, options_for_select([["bonus", "bonus"], ["regular", "regular"]], "regular") %>

  <%= f.text_area :lyrics %>

<%= f.submit "add a track", :class => "btn btn-primary" %>
<% end %>

app/views/tracks/_form_new_v1.html.erb
<!--  /albums/:id  -->

<!-- Form -->
<h2>ADD A TRACK</h2>

<%= bootstrap_form_for track, url: tracks_url, method: "POST", id: "add_track_form" do |f| %>
  <!-- pass album_id as hidden field in case not going through Album#show -->
  <%= f.hidden_field :album_id, value: album.id %>
  <%= f.text_field :name %>
  <%= f.time_select :length %>
  <%= f.select :track_type, options_for_select([["bonus", "bonus"], ["regular", "regular"]], "regular") %>

  <%= f.text_area :lyrics %>

<%= f.submit "add a track", :class => "btn btn-primary" %>
<% end %>

app/views/tracks/_tracks_table.html.erb
<p class="errors"></p>

<table class="table table-hover" id="tracks_table">
      <tr>
        <th></th>
        <th colspan="2">title</th>
      </tr>

	<% album.tracks.reverse.each_with_index do |t, i| %>
		<tr>
			<td style="min-width:30px;"><%= i + 1 %></td>
			<td colspan="2">
				<%= link_to t.name, track_url(t) %>
			</td>
		</tr>
		<tr>
			<td></td>
			<td><%= t.length %></td>
			<td><%= t.track_type %></td>
		</tr>
	<% end %>

</table>

app/views/tracks/_tracks_table_row.html.erb
<tr>
	<td style="min-width:30px;"><%= i %></td>
	<td colspan="2">
		<%= link_to t.name, track_url(t) %>
	</td>
</tr>
<tr>
	<td></td>
	<td><%= t.length %></td>
	<td><%= t.track_type %></td>
</tr>

app/views/tracks/create.html.erb
<h1>Tracks#create</h1>
<p>Find me in app/views/tracks/create.html.erb</p>

app/views/tracks/create.js.erb
var el = $('#tracks_table');

var clear_out_form = function(){

  $('input#track_name').val('');
	$('select#track_length_4i').val('00');
	$('select#track_length_5i').val('00');
	$('select#track_track_type').val('regular');
	$('textarea#track_lyrics').val('');

};

<% if @track.errors.any? %>
  var errors = $('<ul />');
	
  <% @track.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript( error ) %></li>');
  <% end %>
	
  el.find('.errors').html(errors);

<% else %>

  $('#tracks_table').append("<%= escape_javascript( 
	render partial: 'tracks_table_row', locals: { t: @track, i: (@album.tracks.length) } ) %>");

  el.find('.errors').empty();

	clear_out_form();

<% end %>

app/views/tracks/destroy.html.erb
<h1>Tracks#destroy</h1>
<p>Find me in app/views/tracks/destroy.html.erb</p>

app/views/tracks/destroy_note.js.erb
$("#notes_table").replaceWith(function(){
	return $('<div id="notes_table">' + "<%= j( render partial: 'shared/notes_table', locals: { destroy_action: @destroy_url } ) %>" + '</div>');
});

app/views/tracks/edit.html.erb
<h1>Tracks#edit</h1>
<p>Find me in app/views/tracks/edit.html.erb</p>

app/views/tracks/new.html.erb
<h1>Tracks#new</h1>
<p>Find me in app/views/tracks/new.html.erb</p>

app/views/tracks/show.html.erb
<!-- TRACK#show -->

<ol class="breadcrumb" id="nav-crumbs">
  <li><a href="/">HOME</a></li>
  <li <%= 'class="active"' if params[:controller] == 'bands' %>><%= link_to "BANDS", bands_url %></li>
  <li><%= link_to @track.band.name, band_url(@track.band) %></li>
  <li><%= link_to @track.album.name, album_url(@track.album) %></li>
  <li><%= link_to @track.name, track_url(@track) %></li>
</ol>

<!-- main -->
<div class="row title-row">

  <div class="col-lg-7 col-md-7 col-xs-7 col-lg-offset-1 col-md-offset-1 col-xs-offset-1">
    <h1>
     
      <%= @track.name %>
			<%= add_images("#myModal", 1) %>
    </h1>

    <div>
      <%= ugly_lyrics(@track.lyrics) %>
    </div>

    <!-- Display Notes table-->
    <div class="row">
		
			<div id="notes_table">
				<%= render partial: 'notes/notes_table', locals: { owner_notes: @track.notes } %>
    	</div>
			
    </div>


  </div>

  <!-- SIDEBAR RIGHT -->
  <div class="col-lg-3 col-md-3 col-xs-3 sidebar-right">

     <span class="pull-right">
		
		<%= add_edit_icon("#modal_edit_track", 3) %>
			 <%= render partial: 'shared/delete_subject', locals: { action_url: track_url(@track), size: 3 } %>
		</span> 
    
		 

      <!-- ADD A NOTE -->

		<%= render partial: 'notes/form', locals: { track: @track, action_name: notes_url, subj_type: "#{params[:controller].classify}", subj_id: "#{params[:id]}" } %>

  </div>

</div>


<!-- MODAL: edit album -->
<%= render partial: 'modal_edit_track', locals: { track: @track, album: @track.album, band: @track.band } %>
<!-- MODAL: dropzone -->
<%= render partial: 'shared/image_upload', locals: { subject: @track, load_action: load_image_track_url(@track), attach_action: track_url(@track) } %>


<br>

app/views/tracks/update.html.erb
<h1>Tracks#update</h1>
<p>Find me in app/views/tracks/update.html.erb</p>