config/routes.rb
Rails.application.routes.draw do

	resources :images, only: [:create, :destroy]

	resources :users do
		member do
			post 'load_dropzone_images', as: 'load_image'
		end
	end

	resource :session, only: [:new, :create, :destroy]
	resources :bands do
		resources :albums, only: [:new]
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note
		end
	end

	resources :albums, except: [:index] do
		resources :tracks, only: [:new]
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note
		end
	end

	resources :tracks, except: [:index, :new] do
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note # tracks/:id/add_note
		end
	end

	resources :genres, only: [:index, :show]
	
	delete 'notes/:id', to: "notes#destroy", as: :note
	post 'notes', to: "notes#create", as: :notes

	root 'pages#home'

end

app/models/album.rb
class Album < ActiveRecord::Base

	include Imageable
	include Noteable

	belongs_to :band, class_name: "Band", foreign_key: :band_id
	validates :band, presence: true
	validates :album_type, inclusion: { in: ["studio", "live"] }

	has_many :tracks, class_name: "Track", foreign_key: :album_id, inverse_of: :album, dependent: :destroy

	has_many :genre_taggings, inverse_of: :album, dependent: :destroy
	has_many :genres, through: :genre_taggings, source: :genre

	
	def genre_categories #genre names
		Genre.joins(genre_taggings: :album).where('albums.id = ?', self.id).pluck('genres.category').uniq
	end

	def genre_ids #genre names
		Genre.joins(genre_taggings: :album).where('albums.id = ?', self.id).pluck('genres.id').uniq
	end

	# attach when creating a new album
	def attach_genre_taggings(genre_ids)
		return true if genre_ids.empty?

		Album.transaction do
			genre_ids.each do |id|
				self.genre_taggings.create!(genre_id: id)
			end
		end

	end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  respond_to :html, :js, :json

  before_action :require_logged_in
	before_action :set_album, only: [:show, :edit, :update, :destroy]

  def show
		@owner = @album
		@owner_notes = @album.notes
		@owner_id = @album.id
  end

	# only called from outside bands#show
  def new
    @album = Album.new
  end

	# create from bands#show
  def create
		# array of genre_ids (without empty strings)
    genre_ids = album_params[:genre_ids].delete_if(&:empty?).map(&:to_i)
		
		@band = Band.find(album_params[:band_id])
		@album = @band.albums.build(album_params.except(:band_id, :genre_ids))
		
		trans = Transaction do
			@album.save
			@album.attach_genre_taggings(genre_ids)
		end
		
		if trans.valid?
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render 'new'
    end
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
  end

	# NOTABLE

	
	# album_note_url => DELETE /albums/:album_id/notes/:id
  def destroy_note
    @note = Note.find(params[:id])
		@owner = Album.find(params[:album_id])
		@owner_id = @owner.id
		
    @note.destroy
		# refresh
		@owner_notes = @owner.notes
		@destroy_url = "/albums/#{@owner.id}/notes/"
	
		
		respond_to do |format|
			
			format.html { redirect_to :back }
			format.js
		end
    
  end
	
	
  private


  def set_album
    @album = Album.includes(:band).includes(:tracks).find(params[:id])
    @notes = @album.notes
  end

  # band_id passed as hidden input
  def album_params
    params.require(:album).permit(:band_id, :name, :album_type, genre_ids: [])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album_preview.html.erb
<div>
<div class="col-md-4 col-sm-6 portfolio-item">
<!-- 		<a href="#portfolioModal<%= idx %>" class="portfolio-link" data-toggle="modal">
				<div class="portfolio-hover">
						<div class="portfolio-hover-content">
								<i class="fa fa-plus fa-3x"></i>
						</div>
				</div>
				<img src="img/portfolio/golden.png" class="img-responsive" alt="">
		</a> -->
	
<a href="/albums/<%= id %>">
	<%= image_tag("albums/escape-preview.png", class: "img-responsive") %>
	</a>
	<div class="portfolio-caption">
		<a href="/albums/<%= id %>">
			<h4><%= album.name %> </h4>
		</a>
		<p class="text-muted text-genre-tags">
			<% if album.genres.empty? %>
				<br>
			<% else %>
				<%= taggify(album.genres) %>
			<% end %>
		</p>
	</div>

</div>

app/views/albums/_form_new.html.erb
<!-- Add Album modal -->
<div class="portfolio-modal modal fade modal-bands-defaults" tabindex="-1" role="dialog" id="add-album-modal" aria-hidden="true">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 edit-modal-body">
          <div class="modal-body">

            <!-- Form -->
            <h2>Add an Album</h2>

            <%= bootstrap_form_for album, url: albums_url, method: "POST", id: "add_album_form" do |f| %>
            <%= f.text_field :name %>
            <%= f.select :band_id, options_for_select(bands.map{|b| [b.name, b.id] }, band.id), include_blank: true, label: "Band: ", class: "selectpicker" %>
						<%= f.form_group :album_type, label: { text: "Album Type: " } do %>
						<%= f.radio_button :album_type, "studio", label: "studio", checked: true, inline: true, class: "btn-radio" %>
						<%= f.radio_button :album_type, "live", label: "live", inline: true, class: "btn-radio" %>
            <% end %>
            <!-- album[genre_ids][], value: "1"-->
            <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :category, label: "Genre Categories", inline: true %>

            <%= f.submit "submit a new album", :class => "btn btn-primary" %>
            <% end %>

            <!--
            <button type="button" class="btn btn-primary" data-dismiss="modal"> Close</button> -->
          </div><!-- modal-body -->
        </div>
      </div>
    </div><!-- container -->
  </div>
</div>

app/views/albums/_modal_edit_album.html.erb
<!-- Edit Band -->
<div class="portfolio-modal modal fade modal-bands-defaults" tabindex="-1" role="dialog" id="modal_edit_album" aria-hidden="true">
  <div class="modal-content">
    <div class="close-modal" data-dismiss="modal">
      <div class="lr">
        <div class="rl">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 edit-modal-body">
          <div class="modal-body">

            <!-- Form -->
            <h2>Edit <%= album.name %></h2>

            <%= bootstrap_form_for album, url: album_url(album), method: "patch", id: "edit_album_form" do |f| %>
            <%= f.text_field :name %>
            <%= f.select :band_id, options_for_select(bands.map{|b| [b.name, b.id] }, band.id), include_blank: true, label: "Band: ", class: "selectpicker" %>
            <%= f.form_group :album_type, label: { text: "album type" } do %>
            <%= f.radio_button :album_type, "studio", label: "Studio", checked: true %>
            <%= f.radio_button :album_type, "live", label: "Live" %>
            <% end %>
            <!-- album[genre_ids][], value: "1"-->
            <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :category, label: "Genre Category" %>

            <%= f.submit "update album", :class => "btn btn-primary" %>
            <% end %>

            <!--
            <button type="button" class="btn btn-primary" data-dismiss="modal"> Close</button> -->
          </div><!-- modal-body -->
        </div>
      </div>
    </div><!-- container -->
  </div>
</div>

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/destroy_note.js.erb
$("#notes_table").replaceWith(function(){
	return $('<div id="notes_table">' + "<%= j( render partial: 'shared/notes_table', locals: { destroy_action: @destroy_url } ) %>" + '</div>');
});

app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

app/views/albums/new.html.erb
<h1>Albums#new</h1>
<p>Find me in app/views/albums/new.html.erb</p>

app/views/albums/show.html.erb
<ol class="breadcrumb" id="nav-crumbs">
  <li><a href="/">HOME</a></li>
  <li <%= 'class="active"' if params[:controller] == 'bands' %>><%= link_to "BANDS", bands_url %></li>
  <li><%= link_to @album.band.name, band_url(@album.band) %></li>
  <li><%= link_to @album.name, album_url(@album) %></li>
</ol>

<div class="row title-row"> 
		
    <h1>
     
    <%= @album.name %>
		<span class="pull-right">
		<%= add_edit_icon("#modal_edit_album", 1) %>
			<%= render partial: 'shared/delete_subject', locals: { action_url: album_url(@album), size: 1 } %>
			
		</span>
		</h1>	
    
</div>

<!-- MODAL: edit album -->
<%= render partial: 'modal_edit_album', locals: { album: @album, band: @album.band, bands: Band.all } %>
<!-- MODAL: dropzone -->
<%= render partial: 'shared/image_upload', locals: { subject: @album, load_action: load_image_album_url(@album), attach_action: album_url(@album) } %>

<!-- jumbotron -->
<div id="portfolio" class="bg-light-gray">
  <div class="jumbotron" id="band-jumbotron">
    <div class="container">
      <div class="row">

        <div class="col-lg-6 col-md-6 col-xs-6" >
          <% if @album.has_images? %>
          <%= image_tag(@album.profile_pic, class: "band-profile-pic") %>
          <% else %>
          <h2 class="section-heading">
           	 	No images yet
            <br>
            <%= add_images("#myModal", 3) %>
          </h2>
          <% end %>

        </div>
        <div class="col-lg-6 col-md-6 profile-right">
          <h2 class="section-heading">
            <%= @album.band.name %>
          </h2>
          <h2 class="text-genre-tags">
            <%= taggify(@album.genres) %>
          </h2>

          <h3 class="section-subheading text-muted text-center"> <%= @album.album_type %> | <%= @album.description %></h3>
        </div>
      </div>
    </div>
  </div> <!-- jumbotron -->
</div>


<!-- TRACKS -->
<div class="row">

  <!-- main -->
<div class="col-lg-6 col-md-6 col-xs-6 jumbo-col-main">
  <h2>ALL TRACKS </h2>
  <div class="row">
		
			<%= render partial: 'tracks/tracks_table', locals: { album: @album } %>
    
  </div>
</div>

  <!-- SIDEBAR: ADD a track -->
  <div class="col-lg-3 col-md-3 col-xs-3 jumbo-col-right">
    <%= render partial: 'tracks/form_new', locals: { album: @album, track: Track.new } %>
  </div>

</div>
<br>

<!-- NOTES -->
<div class="row">

  <!-- main -->
  <div class="col-lg-6 col-md-6 col-xs-6 jumbo-col-main">

    <div id="notes_table">
			<%= render partial: 'notes/notes_table', locals: { owner_notes: @album.notes } %>
    </div>

  </div>

  <!-- ADD A NOTE -->

  <div class="col-lg-3 col-md-3 col-xs-3 jumbo-col-right">
		<%= render partial: 'notes/form', locals: { album: @album, action_name: notes_url, subj_type: params[:controller].classify, subj_id: params[:id] } %>
  </div>

</div>

app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>