config/routes.rb
Rails.application.routes.draw do

	resources :images, only: [:create, :destroy]

	resources :users do
		member do
			post 'load_dropzone_images', as: 'load_image'
		end
	end

	resource :session, only: [:new, :create, :destroy]
	resources :bands do
		resources :albums, only: [:new]
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note
		end
	end

	resources :albums, except: [:index] do
		resources :tracks, only: [:new]
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note
		end
	end

	resources :tracks, except: [:index, :new] do
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note # tracks/:id/add_note
		end
	end

	resources :genres, only: [:index, :show]
	
	delete 'notes/:id', to: "notes#destroy", as: :note
	post 'notes', to: "notes#create", as: :notes

	root 'pages#home'

end

app/models/band.rb
class Band < ActiveRecord::Base

	include Imageable
	include Noteable

	validates :name, presence: true
	validates :tagline, length: { maximum: 50 }

	belongs_to :submitter, class_name: "User", foreign_key: :submitter_id
		
	has_many :albums, class_name: "Album", foreign_key: :band_id, inverse_of: :band, dependent: :destroy
	has_many :genres, through: :albums, source: :genres

	has_many :members, class_name: "BandMember", foreign_key: :band_id, inverse_of: :band


	scope :recent, ->(num=10) { order('created_at DESC').limit(num) }
	

	def genre_categories
		Genre.joins(genre_taggings: [{ album: :band }]).where('bands.id = ?', self.id).pluck('genres.category').uniq
	end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

	respond_to :html, :js

	before_action :set_band, except: [:index, :new, :create]
	before_action :require_logged_in

  def index
		@bands = Band.all
  end

  def show
		@bands = Band.all
		@album = Album.new
		@owner_id = @band.id
  end

  def new
		@band = Band.new
  end

  def create
		@bands = Band.all
		@band = current_user.submitted_bands.create(band_params)
		if @band.save
			respond_to do |format|
				# format.html { redirect_to band_url(@band)}
				format.js {}
			end
		else
			respond_to do |format|
				# format.html do
				# 	flash[:errors] = @band.errors.full_messages
				# 	redirect_to :back
				# end
				format.js { }
			end
		end
  end

  def edit
  end

  def update
		if @band.update(band_params)
			# flash[:success] = "Successfully updated."
			redirect_to band_url(@band)
		else
			flash[:errors] = @band.errors.full_messages
			redirect_to band_url(@band)
		end
  end

  def destroy
		@band.destroy
		redirect_to root_url
  end

	private

	def set_band
		@band = Band.find(params[:id])
	end

	def band_params
		params.require(:band).permit(:name, :description, :tagline, :date_created)
	end

end

app/helpers/bands_helper.rb
module BandsHelper
	
	def taggify(genres)
		
		html = "<span class='.text-genre-tags'>"
		html += genres.reduce([]) do |memo, genre|
			memo << "<a href='/genres/#{genre.id}' > #{genre.category}</a>"	
			memo
		end.join(" | ")
		
		html += "</span>"
		
		html.html_safe
	end
	
end

app/views/bands/_band_preview.html.erb
<div class="band-preview">
<a href="<%= band_url(band) %>">
  <% if band.has_images? %>
    <%= image_tag(band.profile_thumb) %>
  <% else %>
    <p class="band-profile-default"></p>
  <% end %>
  <%= band.name %>
</a>
</div>

app/views/bands/_edit_modal.html.erb
<!-- Edit Band -->
<div class="portfolio-modal modal fade modal-bands-defaults" tabindex="-1" role="dialog" id="edit-band-modal" aria-hidden="true">
		<div class="modal-content">
				<div class="close-modal" data-dismiss="modal">
						<div class="lr">
								<div class="rl">
								</div>
						</div>
				</div>
	<div class="container">
			<div class="row">
					<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 edit-modal-body">
							<div class="modal-body">

	<!-- Form -->
	<h2>Edit <%= band.name %></h2>

	<%= bootstrap_form_for band, url: band_url(band), method: "patch", id: "edit_band_form" do |f| %>
		<%= f.text_field :name %>
		<%= f.date_field :date_created, label: 'Date Founded' %>
		<%= f.text_area :description %>
		<%= f.submit "update", :class => "btn btn-primary" %>
	<% end %>

<!--
<button type="button" class="btn btn-primary" data-dismiss="modal"> Close</button> -->
										</div><!-- modal-body -->
								</div>
						</div>
				</div><!-- container -->
    </div>
 </div>

app/views/bands/_member_modal.html.erb
<!-- Band Member Modals -->

    <!-- Add images via dropzone -->
    <div class="portfolio-modal modal fade" id="portfolioModal<%= idx %>" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content">
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
													<h2><%= member.name %></h2>
													<p class="item-intro text-muted">
														<%= member.band.name %> 
													</p>
                            <img class="img-responsive" src="band_members/roundicons.png" alt="">
													<p><%= member.description %></p>
                            
                            <ul class="list-inline">
                                <li></li>
                               
                            </ul>
 <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/bands/_member_profile.html.erb
<div class="col-md-4 col-sm-6 portfolio-item">
		<a href="#portfolioModal<%= idx %>" class="portfolio-link" data-toggle="modal">
				<div class="portfolio-hover">
						<div class="portfolio-hover-content">
								<i class="fa fa-plus fa-3x"></i>
						</div>
				</div>
			<!-- replace with real images 
			<img src="/portfolio/roundicons.png" class="img-responsive" alt="">-->
			<%= image_tag('band_members/roundicons.png', class: "img-responsive") %>
			
		</a>
	
		<div class="portfolio-caption">
			<h4><%= member.name %></h4>
			<p class="text-muted text-genre-tags"><%= member.description %></p>
		</div>
</div>

<!-- Band Member Modals -->

    <!-- Add images via dropzone -->
    <div class="portfolio-modal modal fade modal-bands-defaults" id="portfolioModal<%= idx %>" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-content" >
            <div class="close-modal" data-dismiss="modal">
                <div class="lr">
                    <div class="rl">
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-1">
                        <div class="modal-body">
                            <!-- Project Details Go Here -->
													<div class="row">
													<div class="col-lg-4">
														<%= image_tag("band_members/dreams-preview.png", style: "max-width: 200px;") %>
													</div>
														<div class="col-lg-4">
															
													<h2><%= member.name %></h2>
													<p class="item-intro text-muted">
														<%= member.band.name %> 
													</p>
													<p><%= member.description %></p>
                            
													<ul class="list-inline">
															<li></li> 
													</ul>
															
														</div>
													</div>
													
													
													
															
<!--  <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i>Close</button> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/bands/_new.html.erb
<div class="modal-content">
<div class="modal-header">
  <h3>New Band</h3>
</div>
<%= render "new_band_form" %>
</div>

app/views/bands/_new_band_form.html.erb
<div>
  <div class="close-modal" data-dismiss="modal">
    <div class="lr">
      <div class="rl">
      </div>
    </div>
  </div>
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">

    <div class="modal-body" style="padding: 30px;">
      <ul class="errors"></ul>

			<%= form_for @band, remote: true, html: { class: "form-horizontal", style: "display:inline;" } do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :date_created, "Date Formed" %>
        <%= f.date_field :date_created, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :tagline %>
        <%= f.text_field :tagline, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control"  %>
      </div>
			<%= f.submit class: "btn btn-primary" %>
			
			<% end %>
    <!-- TO-DO: accepts nested attributes for members -->
    </div> <!-- modal-body -->

    <div class="modal-footer">
			
      <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
    </div>

  </div>
</div>
</div> <!--modal content-->

app/views/bands/_save.js.erb
$("ul.errors").html("");

<% if @band.errors.any? %>
  <% @band.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
    <% end %>
<% else %>
 
  $(".new-band").html("<%= escape_javascript(render partial: 'band_preview', locals: { band: @band }) %>")
  
  $("#new-band-modal").modal("hide")
<% end %>

app/views/bands/add_note.js.erb
$("#notes_table").replaceWith(function(){
	return $('<div id="notes_table">' + "<%= j( render partial: 'shared/notes_table', locals: { destroy_action: @destroy_url } ) %>" + '</div>');
});

app/views/bands/create.js.erb
<%= render 'save' %>

app/views/bands/edit.html.erb
<%= render partial: 'edit_modal', locals: { band: @band } %>

app/views/bands/index.html.erb
<h1>All Bands</h1>

<ol class="breadcrumb" id="nav-crumbs">
  <li><a href="/">HOME</a></li>
	<li <%= 'class="active"' if params[:controller] == 'bands' %>><a href="#">BANDS</a></li>
</ol>

<!-- hits new.js.erb -->
<div class="row">
  <div class="col-lg-8 col-md-8 col-xs-8 col-lg-offset-2 col-md-offset-2 header-sub-row">
 <%= link_to "Add a Band", new_band_url, remote: true, class: "btn btn-primary" %>
  <!-- ajax div -->
  <div class="new-band text-center"></div>
</div>
</div>

<div class="row">
	<h2>Featured</h2>
  <div class="col-lg-8 col-md-8 col-xs-8 col-lg-offset-2 col-md-offset-2 header-sub-row">
  </div>
</div>

<div class="row">
	<h2>Most Popular</h2>
  <div class="col-lg-8 col-md-8 col-xs-8 col-lg-offset-2 col-md-offset-2 header-sub-row">
  </div>
</div>

<div class="row">
	<h2>Most Recent</h2>
  <div class="col-lg-8 col-md-8 col-xs-8 col-lg-offset-2 col-md-offset-2 header-sub-row">
    <% Band.recent.each do |band| %>
    <%= render partial: 'band_preview', locals: { band: band } %>
    <% end %>
  </div>

</div>

<!-- MODAL: new band form -->
<div id="new-band-modal" class="portfolio-modal modal fade  modal-bands-defaults" aria-hidden="true"></div>

app/views/bands/new.js.erb
// renders _new, which renders _new_band_form
$("#new-band-modal").html("<%= escape_javascript(render 'new') %>")
$("#new-band-modal").modal("show")

app/views/bands/show.html.erb
<ol class="breadcrumb" id="nav-crumbs">
  <li><a href="/">HOME</a></li>
	<li <%= 'class="active"' if params[:controller] == 'bands' %>><%= link_to "BANDS", bands_url %></li>
	<li><%= link_to @band.name, band_url(@band) %></li>
</ol>

<div class="row title-row">
	<div class="col-lg-6 col-md-6 col-xs-6 col-lg-offset-3 col-md-offset-3">
		<h1>
      <%= render partial: 'shared/delete_subject', locals: { action_url: band_url(@band) } %>
      <%= @band.name %>
    </h1>
	</div>

	<!-- right header buttons -->
	<div class="col-lg-3 col-md-3 header-right-btns">
		<button type="button" class="btn btn-info btn-upload btn-edit-header" data-toggle="modal" data-target="#edit-band-modal">edit info</button>
		<span>&nbsp; &nbsp;</span>
    <%= add_images("#myModal") %>

	</div>
</div>

<!-- edit opens in modal -->
<%= render partial: 'edit_modal', locals: { band: @band } %>
<!-- dropzone opens in modal -->
<%= render partial: 'shared/image_upload', locals: { subject: @band, load_action: load_image_band_url(@band), attach_action: band_url(@band) } %>

<!-- jumbotron -->
<div id="portfolio" class="bg-light-gray">
		<div class="jumbotron" id="band-jumbotron">
      <div class="container">
				<div class="row">
					<div class="col-lg-6 col-md-6" >
            <% if @band.has_images? %>
							<%= image_tag(@band.profile_pic, class: "band-profile-pic") %>
            <% else %>
            <h2 class="section-heading">
              No images yet
              <br>
              <%= add_images("#myModal") %>
          </h2>
						<% end %>

					</div>
						<div class="col-lg-6 col-md-6 profile-right">
							<h2 class="section-heading">
									"<%= @band.tagline %>"
							</h2>
							<h2 class="text-genre-tags">
								<%= taggify(@band.genres) %>
							</h2>
							<h3 class="section-subheading text-muted text-center"> <%= @band.description %></h3>
						</div>
				</div>
      </div>
    </div> <!-- jumbotron -->
</div>

<!-- band members -->
<div class="row">
  <h2>Members </h2>
   <div class="row">

  	 <% @band.members.each_with_index do |member, i| %>

  	 	<%= render partial: 'member_profile', locals: { band: @band, member: member, idx: (i+1) } %>

  	 <% end %>
  </div>
</div>

<!-- albums -->
<div class="container text-center">
	<div class="row">
		
<h2>Albums </h2>
			
  <h2><button type="button" class="btn btn-info btn-upload btn-upload-header" data-toggle="modal" data-target="#add-album-modal">add album</button></h2>
	
  <div class="row">

  	 <% @band.albums.each_with_index do |album, i| %>
  	   <%= render partial: 'albums/album_preview', locals: { band: @band, album: album, id: album.id, idx: (i+1) } %>
  	 <% end %>

  </div>

  <!-- modal: add_album form -->
  <%= render partial: 'albums/form_new', locals: { band: @band, bands: @bands, album: @album, load_action: new_album_url } %>
		
	</div>
</div>