config/routes.rb
Rails.application.routes.draw do

	resources :images, only: [:create, :destroy]

	resources :users do
		member do
			post 'load_dropzone_images', as: 'load_image'
		end
	end

	resource :session, only: [:new, :create, :destroy]
	resources :bands do
		resources :albums, only: [:new]
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note
		end
	end

	resources :albums, except: [:index] do
		resources :tracks, only: [:new]
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note
		end
	end

	resources :tracks, except: [:index, :new] do
		member do
			post 'load_dropzone_images', as: 'load_image'
			post 'add_note', as: :add_note # tracks/:id/add_note
		end
	end

	resources :genres, only: [:index, :show]
	
	delete 'notes/:id', to: "notes#destroy", as: :note
	post 'notes', to: "notes#create", as: :notes

	root 'pages#home'

end

app/models/album.rb
class Album < ActiveRecord::Base

	include Imageable
	include Noteable

	belongs_to :band, class_name: "Band", foreign_key: :band_id
	validates :band, presence: true
	validates :album_type, inclusion: { in: ["studio", "live"] }

	has_many :tracks, class_name: "Track", foreign_key: :album_id, inverse_of: :album, dependent: :destroy

	has_many :genre_taggings, inverse_of: :album, dependent: :destroy
	has_many :genres, through: :genre_taggings, source: :genre

	
	def genre_categories #genre names
		Genre.joins(genre_taggings: :album).where('albums.id = ?', self.id).pluck('genres.category').uniq
	end

	def genre_ids #genre names
		Genre.joins(genre_taggings: :album).where('albums.id = ?', self.id).pluck('genres.id').uniq
	end

	# attach when creating a new album
	def attach_genre_taggings(genre_ids)
		return true if genre_ids.empty?

		Album.transaction do
			genre_ids.each do |id|
				self.genre_taggings.create!(genre_id: id)
			end
		end

	end

end

app/models/band.rb
class Band < ActiveRecord::Base

	include Imageable
	include Noteable

	validates :name, presence: true
	validates :tagline, length: { maximum: 50 }

	belongs_to :submitter, class_name: "User", foreign_key: :submitter_id
		
	has_many :albums, class_name: "Album", foreign_key: :band_id, inverse_of: :band, dependent: :destroy
	has_many :genres, through: :albums, source: :genres

	has_many :members, class_name: "BandMember", foreign_key: :band_id, inverse_of: :band


	scope :recent, ->(num=10) { order('created_at DESC').limit(num) }
	

	def genre_categories
		Genre.joins(genre_taggings: [{ album: :band }]).where('bands.id = ?', self.id).pluck('genres.category').uniq
	end

end

app/models/band_member.rb
class BandMember < ActiveRecord::Base
	has_many :images, as: :attachable, dependent: :destroy

	belongs_to :band
	validates :band, :name, presence: true
	validates :name, uniqueness: { scope: :band}
	validates :gender, inclusion: { in: %w(M F) }
	has_many :notes, as: :notable, dependent: :destroy
	
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	
	validates :category, presence: true, uniqueness: true
	
	has_many :genre_taggings, inverse_of: :genre
	has_many :albums, through: :genre_taggings, source: :album
	
	
end

app/models/genre_tagging.rb
class GenreTagging < ActiveRecord::Base
	
	belongs_to :album
	belongs_to :genre
	
	validates :album, :genre, presence: true
	
end

app/models/image.rb
class Image < ActiveRecord::Base
	
	belongs_to :attachable, :polymorphic => true
	
	mount_uploader :attachment, ImageUploader
		
end

app/models/note.rb
class Note < ActiveRecord::Base

  belongs_to :notable, polymorphic: true
		
  validates :content, :notable_id, :notable_type, presence: true

  belongs_to :author, class_name: "User", foreign_key: :user_id
  validates :author, presence: true

end

app/models/track.rb
class Track < ActiveRecord::Base

	include Noteable
	
	validates :name, presence: true

	belongs_to :album
	has_one :band, through: :album, source: :band

	
end

app/models/user.rb
class User < ActiveRecord::Base
	
	include Imageable
	
	has_many :submitted_bands, class_name: "Band", foreign_key: :submitter_id, inverse_of: :submitter
	has_many :submitted_notes, class_name: "Note", foreign_key: :user_id, inverse_of: :author
	
	attr_reader :password # for validating password length
	validates :email, :password_digest, :session_token, presence: true
	validates :email, uniqueness: true
	validates :password, length: { minimum: 6 }, allow_nil: true

	# after User.new or User.find
	after_initialize :ensure_session_token


	def self.generate_session_token
		SecureRandom::urlsafe_base64(16)
	end

	# user_params = {'email' => 'foo', 'password' => 'bar' }
	def self.find_by_credentials(user_params)
		email, password = user_params['email'], user_params['password']
		user = User.find_by(email: email)
		return nil if user.nil?

		user.is_password?(password) ? user : nil
	end

	def reset_session_token!
		self.session_token = User.generate_session_token
		self.save!

		self
	end

	# sets password_digest when User.create(user_params) is called
	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end

	def is_password?(password)
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end


	private

	def ensure_session_token
		self.session_token ||= User.generate_session_token
	end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

	respond_to :html, :js

	before_action :set_band, except: [:index, :new, :create]
	before_action :require_logged_in

  def index
		@bands = Band.all
  end

  def show
		@bands = Band.all
		@album = Album.new
		@owner_id = @band.id
  end

  def new
		@band = Band.new
  end

  def create
		@bands = Band.all
		@band = current_user.submitted_bands.create(band_params)
		if @band.save
			respond_to do |format|
				# format.html { redirect_to band_url(@band)}
				format.js {}
			end
		else
			respond_to do |format|
				# format.html do
				# 	flash[:errors] = @band.errors.full_messages
				# 	redirect_to :back
				# end
				format.js { }
			end
		end
  end

  def edit
  end

  def update
		if @band.update(band_params)
			# flash[:success] = "Successfully updated."
			redirect_to band_url(@band)
		else
			flash[:errors] = @band.errors.full_messages
			redirect_to band_url(@band)
		end
  end

  def destroy
		@band.destroy
		redirect_to root_url
  end

	private

	def set_band
		@band = Band.find(params[:id])
	end

	def band_params
		params.require(:band).permit(:name, :description, :tagline, :date_created)
	end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_errors
		return unless flash[:errors]

		html = "<div style='margin-top: 20px;'><ul>"
		if flash[:errors].is_a?(String)
			html += flash[:errors]
		else
			flash[:errors].each do |error|
				html += "<div class='alert alert-danger'>#{h(error)}</div>"
			end
			html += "</ul></div>"
		end

		html.html_safe
	end

end

app/helpers/bands_helper.rb
module BandsHelper
	
	def taggify(genres)
		
		html = "<span class='.text-genre-tags'>"
		html += genres.reduce([]) do |memo, genre|
			memo << "<a href='/genres/#{genre.id}' > #{genre.category}</a>"	
			memo
		end.join(" | ")
		
		html += "</span>"
		
		html.html_safe
	end
	
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/images_helper.rb
module ImagesHelper

	def add_images(target, size)
		# class='btn btn-info btn-upload btn-upload-header'
		# type='button' 
		html = "<a href data-toggle='modal' style='color: magenta; font-size: #{size}em;' data-target="
    html += "#{target.to_s} >"
    #html += (fa_icon "camera-retro").to_s
		html += ("<i class=\"fa fa-fw fa-camera-retro\"></i>").html_safe
    html += '</a>'

    html.html_safe
  end
	
	def add_edit_icon(target, size)
		# <button type="button" class="btn btn-info btn-upload btn-edit-header" data-toggle="modal" data-target="#modal_edit_album">edit info</button>
		html = "<a href data-toggle='modal' style='font-size: #{size}em;' data-target="
		html += "#{target.to_s} >"
		html += ("<i class=\"fa fa-lg fa-pencil-square-o\ header-edit-btn\"></i>").html_safe
		html += '</a>'
		
		html.html_safe
	end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper

  def ugly_lyrics(lyrics)
    html = "<pre style='text-align:center;'>"
    lyrics.split("\n").each do |line|
      html += "&#9835; #{line}\n"
    end
    html += "</pre>"

    html.html_safe
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="row">
	<div class="col-lg-offset-1 col-md-offset-1">
		
  <small>
    An App Academy doodle by <a href="http://github.com/lishiyo">Connie Li</a>
  </small>
  
		<small class="pull-right" style="margin-right:40px;"><a href="/">project guidelines</a></small>
    	
			
</div>
	</div>
</footer>
	

app/views/layouts/_header.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" id="navbar-header" style="background: <%= params[:controller] == 'pages' ? 'transparent' : 'black'; %>">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="/">bandchamp</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
									<li>
										<%= link_to "Bands", bands_url %>
									</li>
                    <li>
<!--                         <a class="page-scroll" href="#services">Services</a> -->
											<%= link_to "Community", users_url %>
                    </li>
									
									<li>
		<% if current_user.present? %>
									<li><%= link_to "My Profile", user_url(current_user), method: :get %></li>
		<li><%= link_to "Logout", session_url, method: :delete %></li>
	<% else %>
		<li><%= link_to "Login", new_session_url %></li>
		<li><%= link_to "Signup", new_user_url %></li>
	<% end %>
									</li>
<!--                     <li>
                        <a class="page-scroll" href="#portfolio">Portfolio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team">Team</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li> -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/_header_old.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
		<!-- This button inside the navbar-header will replace the full navbar when the screen width gets too narrow, and will toggle a drop-down with the navbar links. -->
		<div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar-collapse">
        <span class="sr-only">toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
		
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="#header-navbar-collapse">
			<%= link_to "bandchamp", root_url, id: "logo" %>
      	<ul class="nav navbar-nav">
					<li><%= link_to "Users", users_url %></li>
					<% if current_user.present? %>
						<li><%= link_to "Logout", session_url, method: :delete %></li>
					<% else %>
						<li><%= link_to "Login", new_session_url %></li>
						<li><%= link_to "Signup", new_user_url %></li>
					<% end %>
				</ul>
  	</div> <!-- div collapse -->
	</div> <!-- div container-fluid -->
	
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>bandchamp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	
<body id="page-top" class="index">
	<%= render 'layouts/header' %>
	
	<% flash.each do |type, message| %>
		<% if type == 'errors' %>
			<%= flash_errors %>
		<% else %>
			<div class="alert alert-#{type}">
				<%= "#{message}" %>
			</div>
		<% end %>
	<% end %>

<%= yield %>

	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<!-- Home page -->
<header>
		<div class="container">
				<div class="intro-text" style="padding-top: 200px;">
						<div class="intro-lead-in">welcome to bandchamp</div>
						<div class="intro-heading">follow all your fav artists and songs</div>
						<a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>
				</div>
		</div>
</header>

<div class="container">
	<div class="row">
	
	</div>
</div>

app/views/shared/_delete_subject.html.erb
<%= link_to raw("<i class=\"fa fa-times-circle\"></i>"), 
		action_url, 
		method: :delete,
		data: { confirm: "Are you sure?" },
style: "display:inline-block; font-size: #{size}em; margin-left: 10px;"
%>

app/views/shared/_form_user.html.erb
<div class="col-md-6 col-md-offset-3">
	<%= form_tag(action_name, method: :post, html: { multipart: true}) do %>

	<%= label_tag 'user[email]', "Email" %>
	<% if user %>
		<%= text_field_tag('user[email]', user.email, class: "form-control") %>
	<% else %>
		<%= text_field_tag('user[email]', nil, class: "form-control") %>
	<% end %>
	<%= label_tag 'user[password]', "Password" %>
	<%= password_field_tag('user[password]', "", class: "form-control") %>

	<%= submit_tag("sign up", class: "btn btn-info") %>
<% end %>
</div>

app/views/shared/_image_upload.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
				<!-- screen reader -->
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Upload Photos</h4>
      </div>

    <div class="modal-body">
			<%= form_tag load_action, method: :post, class: "dropzone", id: "sub_dropzone" do %>
			<div class="fallback">

<!-- 			<input type="hidden" name="image[attachable_type]" value="<%= params[:controller].classify %>" %>
 				<input type="hidden" name="image[attachable_id]" value="<%= params[:id ]%>" %> -->

				<%= file_field_tag "image[attachment]", multiple: true %>
			</div>
		<% end %>

   </div>

			<div class="modal-footer" style="text-align: center; margin: 15px;">

			<!-- hacky way of forcing an attachment to the subject and redirecting to their show page -->
				<%= button_to "upload", attach_action, method: :get, :class => "btn btn-primary", id: "modal-submit-btn" %>
<!--  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
			</div>
		</div>
</div>

</div>

app/views/shared/_nav_crumbs.html.erb
<ol class="breadcrumb" id="nav-crumbs">
  <li><a href="/">HOME</a></li>
	<% if more_links %>
		<% more_links.each do |link| %>
				<li>
				<%= link %>
				</li>
		<% end %>
	<% end %>
</ol>